/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author Leonardo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BT_RegistrarExpediente = new javax.swing.JButton();
        BT_registrarMov = new javax.swing.JButton();
        BT_registrarFinal = new javax.swing.JButton();
        BT_buscarExpediente = new javax.swing.JButton();
        BT_registrarDP = new javax.swing.JButton();
        BT_visualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(700, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BT_RegistrarExpediente.setText("Registrar Expediente");
        BT_RegistrarExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_RegistrarExpedienteActionPerformed(evt);
            }
        });

        BT_registrarMov.setText("Registrar Movimientos");
        BT_registrarMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_registrarMovActionPerformed(evt);
            }
        });

        BT_registrarFinal.setText("Registrar Finalización de Trámite");
        BT_registrarFinal.setToolTipText("");
        BT_registrarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_registrarFinalActionPerformed(evt);
            }
        });

        BT_buscarExpediente.setText("Buscar Expediente");
        BT_buscarExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_buscarExpedienteActionPerformed(evt);
            }
        });

        BT_registrarDP.setText("Registrar dependencia");
        BT_registrarDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_registrarDPActionPerformed(evt);
            }
        });

        BT_visualizar.setText("Visualizar Expedientes Registrados");
        BT_visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_visualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BT_RegistrarExpediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BT_registrarDP, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BT_visualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BT_registrarMov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BT_registrarFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BT_buscarExpediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(254, 254, 254))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(BT_registrarDP)
                .addGap(18, 18, 18)
                .addComponent(BT_RegistrarExpediente)
                .addGap(18, 18, 18)
                .addComponent(BT_visualizar)
                .addGap(45, 45, 45)
                .addComponent(BT_registrarMov)
                .addGap(32, 32, 32)
                .addComponent(BT_registrarFinal)
                .addGap(18, 18, 18)
                .addComponent(BT_buscarExpediente)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_RegistrarExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_RegistrarExpedienteActionPerformed
        // TODO add your handling code here:
        RegistrarExp registrarExp=new RegistrarExp();
        ScreenManager.openNewScreen(this, registrarExp);
    }//GEN-LAST:event_BT_RegistrarExpedienteActionPerformed

    private void BT_registrarMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_registrarMovActionPerformed
        // TODO add your handling code here:
        RegistrarMov registrarMov=new RegistrarMov();
        ScreenManager.openNewScreen(this, registrarMov);
    }//GEN-LAST:event_BT_registrarMovActionPerformed

    private void BT_registrarDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_registrarDPActionPerformed
        // TODO add your handling code here:
        RegistrarDependencia registrarDependencia=new RegistrarDependencia();
        ScreenManager.openNewScreen(this, registrarDependencia);
        
    }//GEN-LAST:event_BT_registrarDPActionPerformed

    private void BT_registrarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_registrarFinalActionPerformed
        // TODO add your handling code here:
        RegistrarFinalizacion registrarFinalizacion= new RegistrarFinalizacion();
        ScreenManager.openNewScreen(this, registrarFinalizacion);
    }//GEN-LAST:event_BT_registrarFinalActionPerformed

    private void BT_buscarExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_buscarExpedienteActionPerformed
        // TODO add your handling code here:
        BuscarExpediente buscarExpediente= new BuscarExpediente();
        ScreenManager.openNewScreen(this, buscarExpediente);
    }//GEN-LAST:event_BT_buscarExpedienteActionPerformed

    private void BT_visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_visualizarActionPerformed
        // TODO add your handling code here:
        VisualizarExpedientes visualizarExpedientes=new VisualizarExpedientes();
        ScreenManager.openNewScreen(this, visualizarExpedientes);
    }//GEN-LAST:event_BT_visualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_RegistrarExpediente;
    private javax.swing.JButton BT_buscarExpediente;
    private javax.swing.JButton BT_registrarDP;
    private javax.swing.JButton BT_registrarFinal;
    private javax.swing.JButton BT_registrarMov;
    private javax.swing.JButton BT_visualizar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
